version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "PythonPrime"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2gz7xh5d8tdn"
s3_prefix = "PythonPrime"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
